FROM ruby:2.3.3
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs imagemagick
RUN mkdir /app
WORKDIR /app

COPY Gemfile /app/Gemfile
# Uncomment except first time
# COPY Gemfile.lock /app/Gemfile.lock
COPY .gemrc /app/.gemrc
RUN bundle install --without production
ADD . /app
