source 'https://rubygems.org'

gem 'rails', '~> 5.0.2'
gem 'mysql2', '>= 0.3.13', '< 0.5'
gem 'puma', '~> 3.0'

# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

#----------------------------------------------------------
# Basis
#----------------------------------------------------------
gem 'coffee-rails', '~> 4.2'
gem 'config'
gem 'jbuilder', '~> 2.5'
gem 'jquery-rails'
gem 'jwt'
gem 'mini_magick'
gem 'sass-rails', '~> 5.0'
gem 'turbolinks', '~> 5'
gem 'uglifier', '>= 1.3.0'

#----------------------------------------------------------
# Model
#----------------------------------------------------------
gem 'enumerize'
gem 'carrierwave', '~> 1.0'
gem 'devise'

#----------------------------------------------------------
# View
#----------------------------------------------------------
gem 'hamlit'
gem 'hamlit-rails'
gem 'kaminari'
gem 'bootstrap', '~> 4.0.0.alpha6'
gem 'rails-assets-tether', '1.1.1'
gem 'font-awesome-rails'
gem 'simple_form'
gem 'gretel'

group :development, :test do
  gem 'byebug', platform: :mri
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'rspec-json_matcher'
  gem 'rspec-rails'
  gem 'spring-commands-rspec'
  gem 'guard'
  gem 'guard-rspec', require: false
  gem 'guard-rubocop'
  gem 'guard-livereload'
  gem 'rubocop', require: false
  gem 'scss_lint', require: false
end

group :development do
  gem 'erb2haml'
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'web-console', '>= 3.3.0'
end
